# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    # Workflow files in .github/workflows will be checked
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: "pip"
    # pyproject.toml will be checked
    directory: "/"
    schedule:
      interval: "weekly"
